name: Docker Image CI/CD for Order Manager

on:
  push:
    branches: ["main"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#   SSH_HOST: ${{ secrets.SSH_HOST }}
#   SSH_USER: ${{ secrets.SSH_USER }}
#   SSH_KEY: ${{ secrets.SSH_KEY }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  IMAGE_NAME: order-manager

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Build and push Backend image
      - name: Build Backend Docker image
        run: |
          docker build ./backend \
            --file ./backend/Dockerfile \
            --tag ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:backend-${GITHUB_REF##*/} \
            --tag ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:backend-latest

      - name: Push Backend Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:backend-${GITHUB_REF##*/}
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:backend-latest

      # Build and push Frontend image
      - name: Build Frontend Docker image
        run: |
          docker build ./frontend \
            --file ./frontend/Dockerfile \
            --tag ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:frontend-${GITHUB_REF##*/} \
            --tag ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:frontend-latest

      - name: Push Frontend Docker image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:frontend-${GITHUB_REF##*/}
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:frontend-latest
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Run deployment command
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ env.SSH_HOST }}
      #     username: ${{ env.SSH_USER }}
      #     key: ${{ env.SSH_KEY }}
      #     script: |
      #       sudo -s
      #       cd /home/azad/projects/rsleather/rsleatherbd-server-main
      #       sudo docker compose down
      #       sudo docker image prune -af
      #       sudo docker compose pull
      #       sudo docker compose up -d

      - name: Deployment Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          username: Order Manager - CI/CD
          details: "✅ Both Frontend and Backend images built and pushed to Docker Hub successfully!"
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}
      - name: Deployment Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: Order Manager - CI/CD
          details: "❌ Build or push failed! Check GitHub Actions logs for details."
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}
      - name: Deployment Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          username: Order Manager - CI/CD
          details: "⚠️ Build and deployment was cancelled!"
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}
